name: Runner SSH (tmate)
on:
  workflow_dispatch:
    inputs:
      note:
        description: why
        default: androide-debug

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start tmate SSH
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
